### ISSUE TITLE
epic: improve gateway conformance coverage

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia-verified-fetch#82]
related to https://github.com/ipfs/service-worker-gateway/issues/224

Chatted with @lidel about this. We should focus on the following order of improvement:

```[tasklist]
### Tasks
- [ ] Fix infinite querying bug (reproducible on some gateway conformance tests that were disabled in https://github.com/ipfs/helia-verified-fetch/pull/81)
- [ ] 100% gateway conformance: TestUnixFSDirectoryListing
- [ ] 100% gateway conformance: TestPathGatewayMiscellaneous
- [ ] 100% gateway conformance: TestGatewayCache
- [ ] 100% gateway conformance: TestGatewayCacheWithIPNS
- [ ] 100% gateway conformance: TestRedirectsFileWithIfNoneMatchHeader
```

**Comment by SgtPooki** [comment]
FYI https://github.com/ipfs/helia-verified-fetch/pull/45 bumped `TestPathGatewayMiscellaneous` GWC from `40%` to `100%` success rate, but dropped `TestDagPbConversion` from `43.08%` to `35.38%`

**Comment by SgtPooki** [comment]
i’m up to 50% success rate on subdomain gateway tests.. I was trying to focus on the order listed at https://github.com/ipfs/helia-verified-fetch/issues/82, but ran into so many issues with network requests not working that should have, I just started diving in where i could

**Comment by SgtPooki** [comment]
I should be able to start on some other tests now that I have most of the gateway-conformance routing issues resolved in the test setup

**Comment by achingbrain** [comment]
Closing as gateway conformance testing is now being done at the service worker gateway level.
